exception in lookup_func global name 'cv2' is not defined
Traceback (most recent call last):
  File "batch_cache.py", line 180, in lookup_func
    image = cv2.imread(path)[:,:,::-1]
NameError: global name 'cv2' is not defined
exception in lookup_func global name 'cv2' is not defined
Traceback (most recent call last):
  File "batch_cache.py", line 180, in lookup_func
    image = cv2.imread(path)[:,:,::-1]
NameError: global name 'cv2' is not defined
